### ISSUE TITLE
bug in the controme.items file, which is generated by the script

### ISSUE THREAD

**Issue by martintamke** [BoBiene/ContromeToOpenHAB#2]
Hello

Thanks for the nice tool.

I found one bug in "Program.cs" and corrected it in a fork. 
the way thetemplate defines items ( [% .2f °C]  & [% .1f °C ] ) in line 69 and 70   is not supported by openhab2. The effect is , that none of the "proxy" items is created in openhab2.

Instead it should be : [% .1f] °C  & [% .2f] °C

I havent merged the fork. This is up  to you

**Comment by BoBiene** [comment]
Fixed in 1.1
